apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: automatic-tern-java-springboot-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/automatic-tern-java-springboot